spring:
  profiles: k8s
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: ${database.host}
    username: ${database.username}
    password: ${database.password}
    driver-class-name: com.mysql.jdbc.Driver
server:
  port: 8000
cloud:
  aws:
    credentials:
      access-key: ${aws.access.key}
      secret-key: ${aws.secret.key}
    region:
      static: ${aws.region}
application:
  bucket:
    name: ${aws.bucket.name}
data:
  save:
    path: ${location}